{% set name = "plotapi" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8228bbd130696e16653b766883ea55ee0586f7c8585c5616faa92dd62edf3186

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.20.0,<3.0.0

test:
  imports:
    - plotapi
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://plotapi.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Engaging visualisations, made easy.

extra:
  recipe-maintainers:
    - shahinrostami
